"""Fixing Term-Election Relationship

Revision ID: 09a747ef881d
Revises: 81d9983a7f35
Create Date: 2025-04-04 19:03:27.877095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a747ef881d'
down_revision: Union[str, None] = '81d9983a7f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('election_term_id_fkey', 'election', type_='foreignkey')
    op.drop_column('election', 'term_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('election_term_id_fkey', 'election', 'term', ['term_id'], ['id'])
    # ### end Alembic commands ###
