"""Create Relationships

Revision ID: 09ef638fc30a
Revises: 19177cc813cf
Create Date: 2025-04-03 10:47:13.131257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ef638fc30a'
down_revision: Union[str, None] = '19177cc813cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('municipality_id', sa.Integer(), nullable=False))
    op.add_column('candidate', sa.Column('election_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'candidate', 'election', ['election_id'], ['id'])
    op.create_foreign_key(None, 'candidate', 'municipality', ['municipality_id'], ['id'])
    op.add_column('deadline', sa.Column('municipality_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deadline', 'municipality', ['municipality_id'], ['id'])
    op.add_column('election', sa.Column('municipality_id', sa.Integer(), nullable=False))
    op.add_column('election', sa.Column('office_id', sa.Integer(), nullable=True))
    op.add_column('election', sa.Column('term_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'election', 'office', ['office_id'], ['id'])
    op.create_foreign_key(None, 'election', 'municipality', ['municipality_id'], ['id'])
    op.create_foreign_key(None, 'election', 'term', ['term_id'], ['id'])
    op.add_column('form', sa.Column('municipality_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'form', 'municipality', ['municipality_id'], ['id'])
    op.add_column('municipality', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'municipality', 'municipality', ['parent_id'], ['id'])
    op.add_column('office', sa.Column('municipality_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'office', 'municipality', ['municipality_id'], ['id'])
    op.add_column('official', sa.Column('municipality_id', sa.Integer(), nullable=False))
    op.add_column('official', sa.Column('office_id', sa.Integer(), nullable=True))
    op.add_column('official', sa.Column('term_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'official', 'municipality', ['municipality_id'], ['id'])
    op.create_foreign_key(None, 'official', 'office', ['office_id'], ['id'])
    op.create_foreign_key(None, 'official', 'term', ['term_id'], ['id'])
    op.add_column('requirement', sa.Column('municipality_id', sa.Integer(), nullable=False))
    op.add_column('requirement', sa.Column('form_id', sa.Integer(), nullable=False))
    op.add_column('requirement', sa.Column('deadline_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'requirement', 'deadline', ['deadline_id'], ['id'])
    op.create_foreign_key(None, 'requirement', 'municipality', ['municipality_id'], ['id'])
    op.create_foreign_key(None, 'requirement', 'form', ['form_id'], ['id'])
    op.add_column('requirement_scope', sa.Column('requirement_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'requirement_scope', 'requirement', ['requirement_id'], ['id'])
    op.add_column('term', sa.Column('election_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'term', 'election', ['election_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'term', type_='foreignkey')
    op.drop_column('term', 'election_id')
    op.drop_constraint(None, 'requirement_scope', type_='foreignkey')
    op.drop_column('requirement_scope', 'requirement_id')
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.drop_constraint(None, 'requirement', type_='foreignkey')
    op.drop_column('requirement', 'deadline_id')
    op.drop_column('requirement', 'form_id')
    op.drop_column('requirement', 'municipality_id')
    op.drop_constraint(None, 'official', type_='foreignkey')
    op.drop_constraint(None, 'official', type_='foreignkey')
    op.drop_constraint(None, 'official', type_='foreignkey')
    op.drop_column('official', 'term_id')
    op.drop_column('official', 'office_id')
    op.drop_column('official', 'municipality_id')
    op.drop_constraint(None, 'office', type_='foreignkey')
    op.drop_column('office', 'municipality_id')
    op.drop_constraint(None, 'municipality', type_='foreignkey')
    op.drop_column('municipality', 'parent_id')
    op.drop_constraint(None, 'form', type_='foreignkey')
    op.drop_column('form', 'municipality_id')
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.drop_column('election', 'term_id')
    op.drop_column('election', 'office_id')
    op.drop_column('election', 'municipality_id')
    op.drop_constraint(None, 'deadline', type_='foreignkey')
    op.drop_column('deadline', 'municipality_id')
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'election_id')
    op.drop_column('candidate', 'municipality_id')
    # ### end Alembic commands ###
