"""Initial Setup

Revision ID: 19177cc813cf
Revises: 
Create Date: 2025-04-03 10:45:04.934148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19177cc813cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRIMARY', 'GENERAL', 'SPECIAL', name='electiontype').create(op.get_bind())
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('PRIMARY', 'GENERAL', 'SPECIAL', name='electiontype', create_type=False), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('elected', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('tenure', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('min_hours', sa.Integer(), nullable=False),
    sa.Column('max_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('official',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contact_form', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('scope', postgresql.ENUM('STATE', 'COUNTY', 'TOWN', 'DISTRICT', name='municipalitytype', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('example')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hello', sa.TEXT(), server_default=sa.text("'world'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='example_pkey')
    )
    op.drop_table('term')
    op.drop_table('requirement_scope')
    op.drop_table('requirement')
    op.drop_table('official')
    op.drop_table('office_template')
    op.drop_table('office')
    op.drop_table('form')
    op.drop_table('election')
    op.drop_table('deadline')
    op.drop_table('candidate')
    sa.Enum('PRIMARY', 'GENERAL', 'SPECIAL', name='electiontype').drop(op.get_bind())
    # ### end Alembic commands ###
