"""Rename Title To Label

Revision ID: 3120ca102a3c
Revises: aa422e1b6149
Create Date: 2025-04-06 15:17:33.386071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3120ca102a3c'
down_revision: Union[str, None] = 'aa422e1b6149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadline', sa.Column('label', sa.String(), nullable=False))
    op.drop_column('deadline', 'title')
    op.add_column('form', sa.Column('label', sa.String(), nullable=False))
    op.drop_column('form', 'title')
    op.add_column('requirement', sa.Column('label', sa.String(), nullable=False))
    op.drop_column('requirement', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('requirement', 'label')
    op.add_column('form', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('form', 'label')
    op.add_column('deadline', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('deadline', 'label')
    # ### end Alembic commands ###
