"""Nullable Office Fields

Revision ID: 41a9896a51a1
Revises: 825926d997d1
Create Date: 2025-04-04 19:49:00.835946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a9896a51a1'
down_revision: Union[str, None] = '825926d997d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('office', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('office', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('office', 'tenure',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('office', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('office', 'min_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('office', 'max_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('office', 'max_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('office', 'min_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('office', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('office', 'tenure',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('office', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('office', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
