"""Election Many to Many Tables

Revision ID: 5156ad566e8d
Revises: 41a9896a51a1
Create Date: 2025-04-05 22:54:39.874852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5156ad566e8d'
down_revision: Union[str, None] = '41a9896a51a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_deadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('deadline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadline.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('election', sa.Column('term_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'election', 'term', ['term_id'], ['id'])
    op.drop_constraint('term_election_id_fkey', 'term', type_='foreignkey')
    op.drop_column('term', 'election_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('term', sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('term_election_id_fkey', 'term', 'election', ['election_id'], ['id'])
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.drop_column('election', 'term_id')
    op.drop_table('election_requirement')
    op.drop_table('election_form')
    op.drop_table('election_deadline')
    # ### end Alembic commands ###
