"""Adding Office To Term

Revision ID: 619c25c376cc
Revises: 5156ad566e8d
Create Date: 2025-04-06 12:27:46.196447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619c25c376cc'
down_revision: Union[str, None] = '5156ad566e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('term', sa.Column('office_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'term', 'office', ['office_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'term', type_='foreignkey')
    op.drop_column('term', 'office_id')
    # ### end Alembic commands ###
