"""Adding join tables back in

Revision ID: 63de9be27c8c
Revises: 4a388bde3be8
Create Date: 2025-04-21 23:16:39.736971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63de9be27c8c'
down_revision: Union[str, None] = '4a388bde3be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MUNICIPALITY', 'ELECTION', name='formtype').create(op.get_bind())
    sa.Enum('MUNICIPALITY', 'ELECTION', name='deadlinetype').create(op.get_bind())
    sa.Enum('MUNICIPALITY', 'ELECTION', name='requirementtype').create(op.get_bind())
    op.create_table('deadline_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deadline_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('parent_type', postgresql.ENUM('MUNICIPALITY', 'ELECTION', name='deadlinetype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('parent_type', postgresql.ENUM('MUNICIPALITY', 'ELECTION', name='formtype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('parent_type', postgresql.ENUM('MUNICIPALITY', 'ELECTION', name='requirementtype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_parent')
    op.drop_table('form_parent')
    op.drop_table('deadline_parent')
    sa.Enum('MUNICIPALITY', 'ELECTION', name='requirementtype').drop(op.get_bind())
    sa.Enum('MUNICIPALITY', 'ELECTION', name='deadlinetype').drop(op.get_bind())
    sa.Enum('MUNICIPALITY', 'ELECTION', name='formtype').drop(op.get_bind())
    # ### end Alembic commands ###
