"""Adding Municipality Website

Revision ID: 81d9983a7f35
Revises: 09ef638fc30a
Create Date: 2025-04-04 18:16:47.568245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d9983a7f35'
down_revision: Union[str, None] = '09ef638fc30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipality', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('municipality', 'website')
    # ### end Alembic commands ###
