"""Fixing Officials

Revision ID: 825926d997d1
Revises: 09a747ef881d
Create Date: 2025-04-04 19:24:36.961911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825926d997d1'
down_revision: Union[str, None] = '09a747ef881d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('official', 'municipality_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('official', 'term_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('official', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('official', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('official', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('official', 'contact_form',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('official', 'contact_form',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('official', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('official', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('official', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('official', 'term_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('official', 'municipality_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
