"""Updating Relationship Constraints

Revision ID: aa422e1b6149
Revises: 8fd90767b330
Create Date: 2025-04-06 13:52:58.941821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa422e1b6149'
down_revision: Union[str, None] = '8fd90767b330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('election_deadline_idx', 'election_deadline', ['election_id', 'deadline_id'])
    op.drop_column('election_deadline', 'id')
    op.create_unique_constraint('election_form_idx', 'election_form', ['election_id', 'form_id'])
    op.drop_column('election_form', 'id')
    op.create_unique_constraint('election_requirement_idx', 'election_requirement', ['election_id', 'requirement_id'])
    op.drop_column('election_requirement', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election_requirement', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('election_requirement_idx', 'election_requirement', type_='unique')
    op.add_column('election_form', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('election_form_idx', 'election_form', type_='unique')
    op.add_column('election_deadline', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('election_deadline_idx', 'election_deadline', type_='unique')
    # ### end Alembic commands ###
