// TODO this list will need to be continually updated
export const columntypes = {
	STRING: "varchar",
	"STRING(100)": "varchar",
	TEXT: "TEXT",
	"TEXT('tiny')": "TEXT",
	"TEXT('medium')": "TEXT",
	"TEXT('long')": "TEXT",
	CHAR: "CHAR(255)",
	"CHAR(100)": "CHAR(100)",
	CITEXT: "CITEXT",
	TSVECTOR: "TSVECTOR",
	BOOLEAN: "BOOL",
	TINYINT: "SMALLINT1",
	"TINYINT.UNSIGNED": "SMALLINT",
	SMALLINT: "SMALLINT",
	"SMALLINT.UNSIGNED": "INTEGER3",
	MEDIUMINT: "INTEGER",
	"MEDIUMINT.UNSIGNED": "INTEGER",
	INTEGER: "int4",
	"INTEGER.UNSIGNED": "int8",
	BIGINT: "int8",
	FLOAT: "REAL",
	"FLOAT.UNSIGNED": "REAL",
	DOUBLE: "DOUBLE PRECISION",
	"DOUBLE.UNSIGNED": "DOUBLE PRECISION",
	DECIMAL: "DECIMAL",
	"DECIMAL(11, 10)": "DECIMAL(11, 10)",
	"DECIMAL(p, s).UNSIGNED": "DECIMAL(p, s)",
	DATE: "TIMESTAMPTZ",
	"DATE(6)": "TIMESTAMP(6) WITH TIME ZONE",
	DATEONLY: "DATE",
	TIME: "TIME",
	"TIME(6)": "TIME(6)",
	NOW: "NOW",
	UUID: "UUID",
	uuidV1: "uuid_generate_v1",
	uuidV4: "pg >= v13: gen_random_uuid\npg < v13: uuid_generate_v4",
	BLOB: "BYTEA",
	"BLOB('tiny')": "BYTEA",
	"BLOB('medium')": "BYTEA",
	"BLOB('long')": "BYTEA",
	JSON: "JSON",
	JSONB: "JSONB",
	GEOMETRY: "GEOMETRY",
	"GEOMETRY('POINT')": "GEOMETRY(POINT)",
	"GEOMETRY('POINT', 4326)": "GEOMETRY(POINT,4326)",
	"GEOMETRY('POLYGON')": "GEOMETRY(POLYGON)",
	"GEOMETRY('LINESTRING')": "GEOMETRY(LINESTRING)",
	GEOGRAPHY: "GEOGRAPHY",
	HSTORE: "HSTORE",
	CIDR: "CIDR",
	INET: "INET",
	MACADDR: "MACADDR",
	MACADDR8: "MACADDR8",
};

export const aliases = {
	bigint: "int8",
	bigserial: "serial8",
	"bit varying": "varbit",
	boolean: "bool",
	character: "char",
	"character varying": "varchar",
	"double precision": "float8",
	integer: "int, int4",
	numeric: "decimal",
	real: "float4",
	smallint: "int2",
	smallserial: "serial2",
	serial: "serial4",
	time: "timetz",
	timestamp: "timestamptz",
};
